export const WALLET_CREATED = "WALLET_CREATED"
export const PIN_VALUE = "PIN_VALUE"
export const SET_PIN = "SET_PIN"
export const SET_THEME = "SET_THEME"
export const REFERRAL_VALUE = "REFERRAL_VALUE"
export const SELECTED_NETWORK= 'SELECTED_NETWORK'
