const ENUMS = {
  SCREENS: {
    CREATE_WALLET: "CREATE_WALLET",
    MNEMONICS_VERIFICATION: "MNEMONICS_VERIFICATION",
    INTRODUCTION_SLIDE: "INTRODUCTION_SLIDE",
    WARNING_SCREEN: "WARNING_SCREEN",
    DASHBOARD: "DASHBOARD",
    IMPORT_WALLET: "IMPORT_WALLET",
    PIN_CODE: "PIN_CODE",
    SPLASH: "SPLASH",
    TRANSFER: "TRANSFER",
    RECEIVE: "RECEIVE",
    SUCCESS: "SUCCESS",
    TRANSACTION_DETAIL: "TRANSACTION_DETAIL",
    ABOUT: "ABOUT",
    SETTING: "SETTING",
    UPDATE_PIN: "UPDATE_PIN",
    WEB_VIEW: "WEB_VIEW",
    BIO: "BIO",
    ALL_TRANSACTION: "ALL_TRANSACTION",
    CHOOSE_IMPORT_OPTION: "CHOOSE_IMPORT_OPTION",
    IMPORT_WALLET_PRIVATE_KEY: "IMPORT_WALLET_PRIVATE_KEY",
    DASHBOARD_MAIN: "DASHBOARD_MAIN",
    PURCHASE: "PURCHASE",
    STAKE: "STAKE",
    SHOW_CONTACT_LIST: "SHOW_CONTACT_LIST",
    ADD_CONTACT_LIST: "ADD_CONTACT_LIST",
    ADD_STAKE: "ADD_STAKE"


  },
  EXTERNAL_URL: {
    NEWS: "https://nitter.net/stabolut",
    TWITTER: "https://twitter.com/stabolut",
    TELEGRAM: "https://t.me/stabolut",
    EXPLORER_URL: "https://sepolia.arbiscan.io/tx/"

  }
}

export default ENUMS;
